global:
  scrape_interval: 35s
  scrape_timeout: 30s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets:
        - 10.11.12.9:9100
        - 10.11.16.9:9100

  - job_name: 'mktxp'
    static_configs:
      - targets: ['10.11.12.9:49090']


